bboard/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from django.views.generic.dates import WeekArchiveView, DayArchiveView
from django.views.generic.edit import CreateView
from rest_framework.routers import DefaultRouter

from bboard.models import Bb
from bboard.views import (APIRubricDetail, APIRubrics, index, by_rubric, BbCreateView,
                          add_and_save, bb_detail, BbRubricBbsView,
                          BbDetailView, BbEditView, BbDeleteView, BbIndexView,
                          BbRedirectView, edit, rubrics, bbs, search, api_rubrics, api_rubric_detail, 
                          APIRubricViewSet, ApiBbViewSet)

app_name = 'bboard'

router = DefaultRouter()
router.register('rubrics', APIRubricViewSet)
router.register('bbs', ApiBbViewSet)

urlpatterns = [
    # path('api/rubrics/<int:pk>/', api_rubric_detail),
    # path('api/rubrics/', api_rubrics),
    # path('api/rubrics/', APIRubrics.as_view()),
    # path('api/rubrics/<int:pk>/', APIRubricDetail.as_view()),
    path('api/', include(router.urls)),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('add/', BbCreateView.as_view(), name='add'),
    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    # path('edit/<int:pk>/', edit, name='edit'),

    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('<int:rubric_id>/',
         BbRubricBbsView.as_view(),
         # cache_page(60 * 5)(BbRubricBbsView.as_view()),
         # cache_page(30)(BbRubricBbsView.as_view()),
         name='by_rubric'),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),

    path('search/', search, name='search'),

    path('', index, name='index'),
    # path('', BbIndexView.as_view(), name='index'),
]

coolsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from coolsite import settings
from women.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

samplesite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('accounts/password_change/', PasswordChangeView.as_view(),
         name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('accounts/password_reset/', PasswordResetView.as_view(),
         name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('testapp/', include('testapp.urls', namespace='testapp')),
    path('todo/', include('todolist.urls', namespace='todo')),

    path('', include('bboard.urls', namespace='bboard')),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.THUMBNAIL_MEDIA_URL,
    #                       document_root=settings.THUMBNAIL_MEDIA_ROOT)

women/urls.py
from django.urls import path, re_path

from .views import *

urlpatterns = [
    path('', WomenHome.as_view(), name='home'),
    path('about/', about, name='about'),
    path('addpage/', AddPage.as_view(), name='add_page'),
    path('contact/', contact, name='contact'),
    path('login/', login, name='login'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', WomenCategory.as_view(), name='category'),
]

bboard/views.py
from django.contrib.auth import get_user, authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.db import transaction, DatabaseError
from django.db.models import Count
from django.forms import modelformset_factory
from django.forms.models import inlineformset_factory
from django.http import (HttpResponse, HttpResponseRedirect, HttpResponseNotFound,
                         Http404, StreamingHttpResponse, FileResponse, JsonResponse)
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.template import loader
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.decorators.cache import cache_page
from django.views.decorators.http import (require_http_methods,
                                          require_GET, require_POST, require_safe)
from django.views.decorators.vary import vary_on_headers, vary_on_cookie
from django.views.generic.base import RedirectView
from django.views.generic.dates import ArchiveIndexView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from bboard.permissions import IsAuthenticatedForAPI, AllowAnyForLogin

from bboard.forms import BbForm, RubricBaseFormSet, SearchForm
from bboard.models import Bb, Rubric, Img
from bboard.serializers import RubricSerializer, BbSerializer
from bboard.signals import add_bb
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

# Основной (вернуть)
# def index(request):
#     bbs = Bb.objects.order_by('-published')
#     # rubrics = Rubric.objects.all()
#     rubrics = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
#     context = {'bbs': bbs, 'rubrics': rubrics}
#
#     return render(request, 'bboard/index.html', context)


# @cache_page(60 * 5)
# @cache_page(30)
# @vary_on_headers('User-Agent')
# @vary_on_headers('Cookie')
# @vary_on_headers('User-Agent', 'Cookie')
# @vary_on_cookie
def index(request):
    bbs = Bb.objects.order_by('-published')
    # rubrics = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)

    paginator = Paginator(bbs, 2)

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1

    page = paginator.get_page(page_num)

    # context = {'bbs': page.object_list, 'rubrics': rubrics, 'page': page}


    # if 'counter' in request.COOKIES:
    #     cnt = int(request.COOKIES['counter']) + 1
    # else:
    #     cnt = 1
    #
    # context = {'bbs': page.object_list, 'page': page, 'counter': cnt}
    #
    # response = render(request, 'bboard/index.html', context)
    # response.set_cookie('counter', cnt)
    # return response

    if 'counter' in request.session:
        cnt = request.session['counter'] + 1
    else:
        cnt = 1

    request.session['counter'] = cnt

    context = {'bbs': page.object_list, 'page': page, 'counter': cnt}

    return render(request, 'bboard/index.html', context)


class BbIndexView(ArchiveIndexView):
    model = Bb
    date_field = 'published'
    date_list_period = 'year'
    template_name = 'bboard/index.html'
    context_object_name = 'bbs'
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(
                                            cnt=Count('bb')).filter(cnt__gt=0)
        return context


class BbRedirectView(RedirectView):
    url = '/'


def by_rubric(request, rubric_id):
    # bbs = Bb.objects.filter(rubric=rubric_id)
    bbs = get_list_or_404(Bb, rubric=rubric_id)
    # rubrics = Rubric.objects.all()
    # rubrics = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
    current_rubric = Rubric.objects.get(pk=rubric_id)

    # bbs = current_rubric.entries.all()

    # context = {'bbs': bbs, 'rubrics': rubrics, 'current_rubric': current_rubric}
    context = {'bbs': bbs, 'current_rubric': current_rubric}

    return render(request, 'bboard/by_rubric.html', context)


# Основной, вернуть
class BbRubricBbsView(ListView):
    template_name = 'bboard/rubric_bbs.html'
    context_object_name = 'bbs'

    def get_queryset(self):
        return Bb.objects.filter(rubric=self.kwargs['rubric_id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['rubrics'] = Rubric.objects.annotate(
        #                                     cnt=Count('bb')).filter(cnt__gt=0)
        context['current_rubric'] = Rubric.objects.get(
                                                   pk=self.kwargs['rubric_id'])
        return context


# class BbRubricBbsView(SingleObjectMixin, ListView):
#     template_name = 'bboard/rubric_bbs.html'
#     pk_url_kwarg = 'rubric_id'
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object(queryset=Rubric)
#         return super().get(request, *args, **kwargs)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['current_rubric'] = self.object
#         context['rubrics'] = Rubric.objects.all()
#         context['bbs'] = context['object_list']
#         return context
#
#     def get_queryset(self):
#         return self.object.bb_set.all()


# Основной (вернуть)
class BbCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = 'bboard/bb_create.html'
    model = Bb
    form_class = BbForm
    success_url = reverse_lazy('bboard:index')
    # initial = {'price': 1000.0}

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        response = super().form_valid(form)
        add_bb.send(sender=self.__class__, instance=self.object)
        return response

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['rubrics'] = Rubric.objects.annotate(
    #                                         cnt=Count('bb')).filter(cnt__gt=0)
    #     return context


def add_and_save(request):
    if request.method == 'POST':
        bbf = BbForm(request.POST)

        # bbf = BbForm(request.POST, request.FILES)

        # bbf = BbForm(request.POST, request.FILES)
        # if bbf.is_valid():
        #     for file in request.FILES.getlist('img'):
        #         img = Img()
        #         img.desc = bbf.cleaned_data['desc']
        #         img.img = file
        #         img.save()

        if bbf.is_valid():
            bbf.save()
            # return HttpResponseRedirect(reverse('bboard:by_rubric',
            #             kwargs={'rubric_id': bbf.cleaned_data['rubric'].pk}))
            return redirect('bboard:by_rubric',
                            rubric_id=bbf.cleaned_data['rubric'].pk)
        else:
            context = {'form': bbf}
            return render(request, 'bboard/bb_create.html', context)
    else:
        # bbf = BbForm(initial={'price': 1000.0})
        bbf = BbForm()
        context = {'form': bbf}
        return render(request, 'bboard/bb_create.html', context)


# Основной, вернуть
class BbEditView(UpdateView):
    model = Bb
    form_class = BbForm
    success_url = reverse_lazy('bboard:index')
    success_message = 'Объявление успешно исправлено!'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['rubrics'] = Rubric.objects.annotate(
    #                                         cnt=Count('bb')).filter(cnt__gt=0)
    #     return context


def edit(request, pk):
    bb = Bb.objects.get(pk=pk)
    if request.method == 'POST':
        bbf = BbForm(request.POST, instance=bb)
        if bbf.is_valid():
            # if bbf.has_changed():
            bbf.save()
            return HttpResponseRedirect(reverse('bboard:by_rubric',
                        kwargs={'rubric_id': bbf.cleaned_data['rubric'].pk}))
        else:
            context = {'form': bbf}
            return render(request, 'bboard/bb_form.html', context)
    else:
        bbf = BbForm(instance=bb)
        context = {'form': bbf}
        return render(request, 'bboard/bb_form.html', context)


def bb_detail(request, bb_id):
    try:
        # bb = Bb.objects.get(pk=bb_id)
        bb = get_object_or_404(Bb, pk=bb_id)
    except Bb.DoesNotExist:
        # return HttpResponseNotFound('Такое объявление не существует')
        return Http404('Такое объявление не существует')

    rubrics = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
    context = {'bb': bb, 'rubrics': rubrics}

    return render(request, 'bboard/bb_detail.html', context)


class BbDetailView(DetailView):
    model = Bb

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['rubrics'] = Rubric.objects.annotate(
    #                                         cnt=Count('bb')).filter(cnt__gt=0)
    #     return context


class BbDeleteView(DeleteView):
    model = Bb
    success_url = '/{rubric_id}/'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['rubrics'] = Rubric.objects.annotate(
    #                                         cnt=Count('bb')).filter(cnt__gt=0)
    #     return context


@login_required(login_url='/login/')

templates/bboard/_rubrics.html
{% extends "layout/basic.html" %}


{% block title %}Правка рубрик{% endblock %}

{% block content %}
<h2>Правка рубрик</h2>

    <form method="post">
    {% csrf_token %}
    {{ formset.as_p }}
    <input type="submit" value="Сохранить">
    </form>

{% endblock %}

templates/bboard/bb_archive_day.html
{% extends "layout/basic.html" %}


{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    {% for bb in bbs %}
    <div>
        <h2>
            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

templates/bboard/bb_archive_week.html
{% extends "layout/basic.html" %}


{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    {% for bb in bbs %}
    <div>
        <h2>
            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

templates/bboard/bb_confirm_delete.html
{% extends "layout/basic.html" %}


{% block title %}Удаление объявления{% endblock %}

{% block content %}
<h2>Удаление объявления</h2>

    <p>Рубрика: {{ bb.rubric.name }}</p>
    <p>Товар: {{ bb.title }}</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Удалить</button>
    </form>
{% endblock %}

templates/bboard/bb_detail.html
{% extends "layout/basic.html" %}
{% load bbcode_tags %}
{% load filtertags %}
{% load thumbnail %}

{% block title %}{{ bb.title }}{% endblock %}

{% block content %}
    <div>
        {% if bb.rubric %}
        <p>Рубрика: <a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
                                                {{ bb.rubric.name }}</a></p>
        {% endif %}

        <h2>{{ bb.title }}</h2>

        {% if bb.img %}
        <p>
{#            <img src="{{ bb.img.url }}" alt="{{ bb.title }}" title="{{ bb.title }}">#}
{#            <img src="{{ bb.img|thumbnail_url:'default' }}" alt="{{ bb.title }}" title="{{ bb.title }}">#}
{#            <img src="{% thumbnail bb.img 'default' %}" alt="{{ bb.title }}" title="{{ bb.title }}">#}
{#            <img src="{% thumbnail bb.img 'default' bw=True %}" alt="{{ bb.title }}" title="{{ bb.title }}">#}
            <img src="{% thumbnail bb.img '300x200' crop='smart' %}" alt="{{ bb.title }}" title="{{ bb.title }}">
        </p>
        {% endif %}

        <p>{% bbcode bb.content %}</p>
        <p>Цена: <strong>{{ bb.price|cur:'руб.' }}</strong></p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>

{#        {% if bb.img %}#}
{#            {% for img in imgs %}#}
{#                <div><img src="{{ img.img.url }}"></div>#}
{#            {% endfor %}#}
{#        {% endif %}#}

        <p>
            <a href="{% url 'bboard:edit' bb.pk %}">Изменить</a> |
            <a href="{% url 'bboard:delete' bb.pk %}">Удалить</a>
        </p>
    </div>
{% endblock %}

templates/bboard/bb_form.html
{% extends "layout/basic.html" %}


{% block title %}Изменение объявления{% endblock %}

{% block content %}

    {% if messages %}
        <ul class="messages messagelist">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
        </ul>
    {% endif %}

<h2>Изменение объявления</h2>
    {% if form.is_multipart %}
        <form method="post" enctype="multipart/form-data">
    {% else %}
        <form method="post">
    {% endif %}
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% if form.non_field_errors %}
            <ul>
                {% for error in form.non_field_errors %}
                    <li><em>{{ error|escape }}</em></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% for field in form.visible_fields %}
            {% if field.errors %}
                <ul>
                    {% for error in field.errors %}
                        <li><em>{{ error|escape }}</em></li>
                    {% endfor %}
                </ul>
            {% endif %}
                <p>{{ field.label_tag }}<br>{{ field }}<br>
                    {{ field.help_text }}</p>
        {% endfor %}

        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

templates/bboard/bbs.html
{% extends "layout/basic.html" %}


{% block title %}Изменение объявлений рубрики {{ current_rubric }}{% endblock %}

{% block content %}
    <h2>Изменение объявлений рубрики {{ current_rubric }}</h2>

    <form method="post">
        {% csrf_token %}
        {{ formset.as_p }}
        <p><button type="submit" class="btn btn-primary">Сохранить</button></p>
    </form>

{% endblock %}

templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}


{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    {% for bb in bbs %}
    {% url 'bboard:detail' bb.pk as detail_url %}
    <div>
        <h2>
{#            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title }}</a>#}
{#            <a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a>#}
        <a href="{{ detail_url }}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

templates/bboard/create.html
{% extends "layout/basic.html" %}


{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

templates/bboard/index.html
{% extends "layout/basic.html" %}
{% load bbcode_tags %}
{% load django_bootstrap5 %}

{% block content %}
    {% if messages %}
        <ul class="messages messagelist">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
        </ul>
    {% endif %}

    <p>Counter: {{ counter }}</p>

    {#    {{ block.super }} #}

    {% with bb_count=bbs.count %}
        {% if bb_count > 0 %}
            <p>Всего {{ bb_count }} объявлений.</p>
        {% endif %}
    {% endwith %}

    {% for bb in bbs %}
        <div>
            <h2>
                <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title_and_price }}</a>
            </h2>

{#            <p>{{ bb.content }}</p>#}
            <p>{% bbcode bb.content %}</p>

            {% if bb.rubric %}
            <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
                {{ bb.rubric.name }}</a></p>
            {% endif %}


            <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        </div>
    {% endfor %}

    {% bootstrap_pagination page size='sm' pages_to_show=5 %}

{% endblock %}

templates/bboard/rubric_bbs.html
{% extends "layout/basic.html" %}
{% load bbcode_tags %}

{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    <h2>Рубрика: {{ current_rubric.name }}</h2>
    {% for bb in bbs %}
    {% url 'bboard:detail' bb.pk as detail_url %}
    <div class="{% cycle 'bb1' 'bb2' %}">
        {% if forloop.first %}
            <h2 style="font-size: 48px;">{{ forloop.counter }}.
                {% comment 'Доделать до завтра' %}
    {#            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title }}</a>#}
    {#            <a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a>#}
                {% endcomment %}
                <a href="{{ detail_url }}">{{ bb.title }}</a>
            </h2>
        {% else %}
            <h2>{{ forloop.counter }}.
                <a href="{{ detail_url }}">{{ bb.title }}</a>
            </h2>
        {% endif %}
{#        <p>{{ bb.content|truncatewords:3 }}</p>#}
{#        <p>{{ bb.content }}</p>#}
        <p>{% bbcode bb.content %}</p>

        {% ifchanged bb.rubric.pk %}
            <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
                {{ bb.rubric.name }}</a></p>
        {% endifchanged %}

        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>

        {% firstof bb.phone bb.email 'На деревню дедушке' %}
    </div>
    {% empty %}
        <p>Объявлений нет</p>
    {% endfor %}

    {% comment %}
        {% lorem 5 p %}
        {% debug %}
    {% endcomment %}

{% endblock %}

templates/bboard/rubrics.html
{% extends "layout/basic.html" %}
{% load django_bootstrap5 %}

{% block title %}Правка рубрик{% endblock %}

{% block content %}
<h2>Правка рубрик</h2>

    <form method="post">
        {% csrf_token %}

        {% bootstrap_formset formset %}
        {% bootstrap_button 'Сохранить' %}
        {% bootstrap_button 'Очистить' button_type='reset' button_class='btn-secondary' %}

    </form>

{% endblock %}

templates/bboard/search.html
{% extends "layout/basic.html" %}

{% block title %}Поиск объявлений{% endblock %}

{% block content %}
<h2>Поиск объявлений</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Искать</button>
    </form>
{% endblock %}

templates/bboard/search_results.html
{% extends "layout/basic.html" %}

{% block title %}Поиск объявлений{% endblock %}

{% block content %}

    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
        </ul>
    {% endif %}

    <h2>Поиск объявлений</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Искать</button>
    </form>

    {% for bb in bbs %}
    <div>
        <h2>
            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}