bboard/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from django.views.generic.dates import WeekArchiveView, DayArchiveView
from django.views.generic.edit import CreateView
from rest_framework.routers import DefaultRouter

from bboard.models import Bb
from bboard.views import (APIRubricDetail, APIRubrics, index, by_rubric, BbCreateView,
                          add_and_save, bb_detail, BbRubricBbsView,
                          BbDetailView, BbEditView, BbDeleteView, BbIndexView,
                          BbRedirectView, edit, rubrics, bbs, search, api_rubrics, api_rubric_detail, 
                          APIRubricViewSet, ApiBbViewSet)

app_name = 'bboard'

router = DefaultRouter()
router.register('rubrics', APIRubricViewSet)
router.register('bbs', ApiBbViewSet)

urlpatterns = [
    # path('api/rubrics/<int:pk>/', api_rubric_detail),
    # path('api/rubrics/', api_rubrics),
    # path('api/rubrics/', APIRubrics.as_view()),
    # path('api/rubrics/<int:pk>/', APIRubricDetail.as_view()),
    path('api/', include(router.urls)),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('add/', BbCreateView.as_view(), name='add'),
    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    # path('edit/<int:pk>/', edit, name='edit'),

    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('<int:rubric_id>/',
         BbRubricBbsView.as_view(),
         # cache_page(60 * 5)(BbRubricBbsView.as_view()),
         # cache_page(30)(BbRubricBbsView.as_view()),
         name='by_rubric'),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),

    path('search/', search, name='search'),

    path('', index, name='index'),
    # path('', BbIndexView.as_view(), name='index'),
]

coolsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from coolsite import settings
from women.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

samplesite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('accounts/password_change/', PasswordChangeView.as_view(),
         name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('accounts/password_reset/', PasswordResetView.as_view(),
         name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('testapp/', include('testapp.urls', namespace='testapp')),
    path('todo/', include('todolist.urls', namespace='todo')),

    path('', include('bboard.urls', namespace='bboard')),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.THUMBNAIL_MEDIA_URL,
    #                       document_root=settings.THUMBNAIL_MEDIA_ROOT)

todolist/urls.py
from django.urls import path

from todolist.views import todo_list, todo_detail, todo_create, todo_update, todo_delete

app_name = 'todolist'

urlpatterns = [
    path('', todo_list, name='todo_list'),
    path('<int:todo_id>/', todo_detail, name='todo_detail'),
    path('create/', todo_create, name='todo_create'),
    path('update/<int:todo_id>/', todo_update, name='todo_update'),
    path('delete/<int:todo_id>/', todo_delete, name='todo_delete'),
]

women/urls.py
from django.urls import path, re_path

from .views import *

urlpatterns = [
    path('', WomenHome.as_view(), name='home'),
    path('about/', about, name='about'),
    path('addpage/', AddPage.as_view(), name='add_page'),
    path('contact/', contact, name='contact'),
    path('login/', login, name='login'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', WomenCategory.as_view(), name='category'),
]

todolist/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Задача',
    )

todolist/forms.py
from django.forms import ModelForm

from todolist.models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'

todolist/views.py
from django.shortcuts import render

def todo_list(request):
    pass

def todo_detail(request, todo_id):
    pass


def todo_create(request):
    pass

def todo_update(request, todo_id):
    pass


def todo_delete(request, todo_id):
    pass

templates/todolist/by_rubric.html
{% extends "layout/basic.html" %}


{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    {% for bb in bbs %}
    <div>
        <h2>
            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

templates/todolist/create.html
{% extends "layout/basic.html" %}



{% block title %}Добавление{% endblock %}

{% block content %}
<h2>Добавление</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

templates/todolist/index.html
{% extends "layout/basic.html" %}

{% block content %}
    {% for bb in bbs %}
    <div>
{#        <h2>{{ bb.title }}</h2>#}
        <h2>
            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title_and_price }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
            {{ bb.rubric.name }}</a></p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

templates/todolist/todo_create.html
{% extends "layout/basic.html" %}


{% block title %}Добавление задачи{% endblock %}

{% block content %}
<h2>Добавление задачи</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

templates/todolist/todo_detail.html
{% extends "layout/basic.html" %}


{% block title %}{{ bb.title }}{% endblock %}

{% block content %}
    <div>
        <h2>{{ bb.title }}</h2>
        <p>{{ bb.content }}</p>
        <p>Цена: <strong>{{ bb.price }}</strong> тг.</p>
        <p>
            <a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
                {{ bb.rubric.name }}</a>
        </p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
{% endblock %}